# Generated by Django 5.2.17 on 2026-09-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده / آماده بررسی'), ('processing', 'در حال بسته\u200cبندی در انبار'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده')], default='pending_payment', max_length=30, verbose_name='وضعیت')),
                ('shipping_method', models.CharField(choices=[('tipax', 'تیپاکس (پس\u200cکرایه)'), ('post', 'پست پیشتاز'), ('courier', 'پیک موتوری فوری (ویژه تهران)'), ('freight', 'باربری ترمینال'), ('pickup', 'تحویل حضوری از انبار')], max_length=30, verbose_name='روش ارسال')),
                ('vin_or_chassis', models.CharField(blank=True, max_length=100, verbose_name='شماره شاسی / VIN')),
                ('vin_verified', models.BooleanField(default=False, verbose_name='شاسی تاییدشده')),
                ('admin_verification_note', models.TextField(blank=True, verbose_name='یادداشت کارشناس درباره تطابق شاسی')),
                ('shipping_address', models.TextField(verbose_name='آدرس ارسال')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('subtotal', models.BigIntegerField(default=0, verbose_name='جمع اقلام (تومان)')),
                ('shipping_cost', models.BigIntegerField(default=0, verbose_name='هزینه ارسال (تومان)')),
                ('total_amount', models.BigIntegerField(verbose_name='مبلغ کل (تومان)')),
                ('payment_tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری پرداخت')),
                ('shipping_tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_token', models.CharField(db_index=True, max_length=64, verbose_name='توکن سبد')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='زمان انقضا')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='قطعه')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant', verbose_name='تنوع')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'قفل سبد',
                'verbose_name_plural': 'قفل\u200cهای سبد',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='عنوان قطعه (ثبت لحظه خرید)')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.BigIntegerField(verbose_name='قیمت واحد (تومان)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product', verbose_name='قطعه')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant', verbose_name='تنوع')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
    ]
