# Generated by Django 5.2.17 on 2026-09-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='makes/')),
            ],
            options={
                'verbose_name': 'خودروساز',
                'verbose_name_plural': 'خودروسازها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='نام آیکون (مثلاً disc, zap)', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand', models.CharField(max_length=100, verbose_name='برند')),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='کد فنی')),
                ('isaco_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='کد ایساکو')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('stock', models.IntegerField(default=0, verbose_name='موجودی')),
                ('low_stock_threshold', models.IntegerField(default=2, verbose_name='آستانه موجودی کم')),
                ('is_call_for_price', models.BooleanField(default=False, verbose_name='استعلام قیمت')),
                ('max_order_quantity', models.IntegerField(default=5, verbose_name='حداکثر تعداد در سفارش')),
                ('warranty_text', models.CharField(default='ضمانت اصالت و سلامت فیزیکی', max_length=200, verbose_name='متن ضمانت')),
                ('is_genuine', models.BooleanField(default=True, verbose_name='اصل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر شاخص')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, max_length=350, verbose_name='توضیحات سئو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PriceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.BigIntegerField(verbose_name='قیمت قبلی')),
                ('new_price', models.BigIntegerField(verbose_name='قیمت جدید')),
                ('changed_by', models.CharField(default='admin', max_length=100, verbose_name='تغییردهنده')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='catalog.product', verbose_name='قطعه')),
            ],
            options={
                'verbose_name': 'سابقه قیمت',
                'verbose_name_plural': 'سابقه قیمت\u200cها',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='قطعه')),
            ],
            options={
                'verbose_name': 'تصویر قطعه',
                'verbose_name_plural': 'تصاویر قطعات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('sku_modifier', models.CharField(blank=True, max_length=50, verbose_name='پسوند کد')),
                ('price_override', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت اختصاصی (تومان)')),
                ('stock', models.IntegerField(default=0, verbose_name='موجودی')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='قطعه')),
            ],
            options={
                'verbose_name': 'تنوع قطعه',
                'verbose_name_plural': 'تنوع\u200cهای قطعه',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(unique=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.vehiclemake', verbose_name='خودروساز')),
            ],
            options={
                'verbose_name': 'مدل خودرو',
                'verbose_name_plural': 'مدل\u200cهای خودرو',
                'ordering': ['make__id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField()),
                ('year_start', models.IntegerField(blank=True, null=True, verbose_name='سال شروع')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='سال پایان')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='catalog.vehiclemodel', verbose_name='مدل خودرو')),
            ],
            options={
                'verbose_name': 'تیپ خودرو',
                'verbose_name_plural': 'تیپ\u200cهای خودرو',
                'ordering': ['vehicle_model__id', 'id'],
                'unique_together': {('vehicle_model', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_trims',
            field=models.ManyToManyField(blank=True, related_name='compatible_products', to='catalog.vehicletrim', verbose_name='تیپ\u200cهای سازگار'),
        ),
    ]
